---
- hosts: mpi_nodes
  tasks:
  - name: install openmpi
    apt:
      name:
        - openmpi-bin
        - libopenmpi-dev
        - gcc
        - make
      state: latest
      update_cache: true
    become: yes
    become_method: sudo
